POST http://localhost:3000/client
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john@doe.com",
  "reminderFrequency": "annual",
  "lastReminder": "2019-02-01T00:00:00.000Z"
}

###